language: cpp
git:
  depth: 50
  submodules: true
exclude:
  - if: branch = continous
jobs:
  include:
  - stage: publish
    name: Retag and publish game
    arch: arm64
    os: linux
    dist: bionic
    if: branch = master
    script: skip
    before_deploy:
      # Set up git user name and tag this commit
      - git config --local user.name "CSMoE-Deployer"
      - git config --local user.email "824395314@qq.com"
      - export TRAVIS_TAG=continuous
      - git remote add travis-deploy-public https://${GITHUB_TOKEN}@github.com/MoeMod/CSMoE.git
      - git tag --delete $TRAVIS_TAG || echo "tag not exists..."
      - git push travis-deploy-public --delete $TRAVIS_TAG
      - git tag --force $TRAVIS_TAG
      - git push travis-deploy-public --tags --force
    deploy:
      provider: script
      api_key: ${GITHUB_TOKEN}
      script: echo "I am publishing !!!"
      on:
        branch: master
        repo: MoeMod/CSMoE
      overwrite: true
      skip_cleanup: true
      prerelease: true
  - stage: build
    name: Build for Linux amd64
    arch: amd64
    os: linux
    dist: bionic
    cache: ccache
    language: cpp
    compiler: gcc
    sudo: true
    addons:
      apt:
        packages:
        - cmake
        - x11-utils
        - libgl1-mesa-dev
        - libegl1-mesa-dev
        - libgles2-mesa-dev
    before_script:
    - export ARCH=x86_64
    - sudo apt-get install libsdl2-dev
    - sudo apt-get install libsdl2-image-dev
    - sudo apt-get install libfontconfig1-dev
    script:
    - sh scripts/build_portable_linux_engine.sh;
  - stage: build
    name: Build for Linux arm64
    arch: arm64
    os: linux
    dist: bionic
    cache: ccache
    language: cpp
    compiler: gcc
    sudo: true
    addons:
      apt:
        packages:
        - cmake
        - x11-utils
        - libgl1-mesa-dev
        - libegl1-mesa-dev
        - libgles2-mesa-dev
    before_script:
    - sudo apt-get install libsdl2-dev
    - sudo apt-get install libsdl2-image-dev
    - sudo apt-get install libfontconfig1-dev
    script:
    - sh scripts/build_portable_linux_engine.sh;
  - stage: build
    name: Build for macOS amd64 and deploy
    cache: ccache
    os: osx
    osx_image: xcode11
    language: cpp
    compiler: clang
    before_script:
    - curl -s https://www.libsdl.org/release/SDL2-2.0.10.dmg > SDL2.dmg
    - hdiutil attach SDL2.dmg
    - mkdir -p ~/Library/Frameworks
    - cp -r /Volumes/SDL2/SDL2.framework ~/Library/Frameworks/
    - brew install p7zip
    - curl -fLO https://github.com/MoeMod/CSMoE-GameDir/releases/download/continuous/CSMoE-CD-GameDir-Full.7z
    - 7z x CSMoE-CD-GameDir-Full.7z
    script:
    - mkdir -p osx-build && cd osx-build
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - cmake --build . --target csmoe_cpack_dmg -j 4
    - cd ..
    before_deploy:
    - cp osx-build/CSMoE-macOS-x86_64.dmg CSMoE-CD-macOS-x86_64-unsigned-Full.dmg
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file:
        - CSMoE-CD-macOS-x86_64-unsigned-Full.dmg
      on:
        branch: master
        repo: MoeMod/CSMoE
      overwrite: true
      skip_cleanup: true
      prerelease: true
  - stage: build
    name: Build for iOS and deploy
    os: osx
    osx_image: xcode11
    language: objective-c
    before_script:
    - curl -s http://libsdl.org/release/SDL2-2.0.10.tar.gz > SDL2.tar.gz
    - tar xzf SDL2.tar.gz
    - mv SDL2-2.0.10 SDL2
    - brew install p7zip
    - curl -fLO https://github.com/MoeMod/CSMoE-GameDir/releases/download/continuous/CSMoE-CD-GameDir-Full.7z
    - 7z x CSMoE-CD-GameDir-Full.7z
    script:
    - set -o pipefail && xcodebuild archive -project Xcode-iOS/CSMoE-iOS.xcodeproj -scheme CSMoE-iOS -configuration Release -archivePath ./CSMoE-iOS.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    - mkdir -p Payload
    - cp -a ./CSMoE-iOS.xcarchive/Products/Applications/csmoe-ios.app Payload/
    before_deploy:
      - zip -r CSMoE-CD-iOS-universal-unsigned-Full.ipa Payload
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file:
        - CSMoE-CD-iOS-universal-unsigned-Full.ipa
      on:
        branch: master
        repo: MoeMod/CSMoE
      overwrite: true
      skip_cleanup: true
      prerelease: true
  - stage: build
    name: Build for Android and deploy
    language: android
    dist: trusty
    android:
      components:
      - build-tools-28.0.3
      - android-29
      - extra
      - add-on
      - tools
    before_script:
    - echo y | /usr/local/android-sdk/tools/bin/sdkmanager "patcher;v4"
    - echo y | /usr/local/android-sdk/tools/bin/sdkmanager ndk-bundle
    - sudo apt-get install p7zip-full
    - curl -fLO https://github.com/MoeMod/CSMoE-GameDir/releases/download/continuous/CSMoE-CD-GameDir-Full.7z
    - 7z x CSMoE-CD-GameDir-Full.7z
    script:
    - cd Android
    - "./gradlew assembleRelease"
    - cd ..
    before_deploy:
      - cp Android/app/build/outputs/apk/release/app-release-unsigned.apk CSMoE-CD-Android-arm64-Full-unsigned.apk
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file:
        - CSMoE-CD-Android-arm64-Full-unsigned.apk
      on:
        branch: master
        repo: MoeMod/CSMoE
      overwrite: true
      skip_cleanup: true
      prerelease: true
  - stage: build
    name: Build for Win32 amd64 MSVC/CMake
    cache: ccache
    os: windows
    language: cpp
    before_script:
    - curl http://libsdl.org/release/SDL2-devel-2.0.10-VC.zip -o SDL2.zip
    - unzip SDL2.zip
    - mv SDL2-2.0.10 SDL2
    script:
    - sh scripts/build_windows_engine.sh
